// === FONZA-CUSTOM ============================================================
// Not part of upstream Bannerlord-Coop. Owned by this fork (JustinRMGC).
// Fonza Launcher / Coop server console.  Docs: /custom/CLAUDE.md
// =============================================================================

using Common;
using Common.Logging;
using Coop.Core.Server.Connections;
using GameInterface;
using GameInterface.Services.GameState.Interfaces;
using GameInterface.Services.Heroes.Enum;
using GameInterface.Services.Heroes.Interaces;
using GameInterface.Services.ObjectManager;
using GameInterface.Services.Players;
using GameInterface.Services.Players.Data;
using GameInterface.Services.Save.Commands;
using LiteNetLib;
using Serilog;
using System;
using System.Collections.Generic;
using System.IO;
using System.Text;
using TaleWorlds.CampaignSystem;
using TaleWorlds.Localization;

namespace Coop.Core.Server.Admin
{
    /// <summary>
    /// Optional server-side bridge for the external CoopServerConsole control panel.
    /// It is a plain <see cref="IUpdateable"/> pumped on the game thread, so it can touch the
    /// campaign directly. It does two things, entirely through files in the engine working
    /// directory (next to the logs) so no socket/port/firewall is involved:
    ///   * writes a status snapshot (state + connected players) ~1×/second
    ///   * consumes single admin commands (kick/save/pause/resume/speed/menu) and writes an ack
    ///
    /// Every operation is wrapped so a failure here can never disturb normal play; if anything
    /// throws the bridge just logs and keeps going. It is only added to the update loop on a
    /// server (see CoopMod), and does nothing until a campaign is actually running.
    /// </summary>
    public sealed class ConsoleControlBridge : IUpdateable
    {
        public const string StatusFileName = "coop_console_status.txt";
        public const string CommandFileName = "coop_console_command.txt";
        public const string AckFileName = "coop_console_ack.txt";

        private static readonly ILogger Logger = LogManager.GetLogger<ConsoleControlBridge>();

        private readonly string statusPath;
        private readonly string commandPath;
        private readonly string ackPath;

        private double statusAccum;
        private double commandAccum;
        private bool announced;

        public ConsoleControlBridge()
        {
            var dir = SafeCwd();
            statusPath = Path.Combine(dir, StatusFileName);
            commandPath = Path.Combine(dir, CommandFileName);
            ackPath = Path.Combine(dir, AckFileName);
        }

        public int Priority => 0;

        public void Update(TimeSpan frameTime)
        {
            try
            {
                if (!announced)
                {
                    announced = true;
                    Logger.Information("[ConsoleBridge] Active — status at {Path}", statusPath);
                }

                commandAccum += frameTime.TotalSeconds;
                if (commandAccum >= 0.25)
                {
                    commandAccum = 0;
                    TryProcessCommand();
                }

                statusAccum += frameTime.TotalSeconds;
                if (statusAccum >= 1.0)
                {
                    statusAccum = 0;
                    WriteStatus();
                }
            }
            catch (Exception ex)
            {
                // Never let the console bridge affect the game loop.
                Logger.Verbose(ex, "[ConsoleBridge] Update failed (ignored)");
            }
        }

        // ------------------------------------------------------------------ status

        private void WriteStatus()
        {
            var sb = new StringBuilder();
            sb.AppendLine("# CoopServerConsole status (auto-generated by the mod)");
            sb.AppendLine("updated=" + DateTime.Now.ToString("HH:mm:ss"));

            bool campaignUp = false;
            try { campaignUp = Campaign.Current != null; } catch { }
            sb.AppendLine("state=" + (campaignUp ? "Campaign running" : "Main menu / loading"));

            int count = 0;
            try { count = AppendPlayers(sb); } catch (Exception ex) { Logger.Verbose(ex, "[ConsoleBridge] player enumerate failed"); }
            sb.AppendLine("players=" + count);

            SafeWrite(statusPath, sb.ToString());
        }

        /// <summary>Appends one player= line per connected peer. Returns the count.</summary>
        private int AppendPlayers(StringBuilder sb)
        {
            if (!ContainerProvider.TryResolve<IConnectionCollection>(out var connections) || connections == null)
                return 0;

            ContainerProvider.TryResolve<IPlayerManager>(out var players);
            ContainerProvider.TryResolve<IObjectManager>(out var objects);

            int count = 0;
            foreach (var kvp in EnumerateConnections(connections))
            {
                var peer = kvp.Key;
                var logic = kvp.Value;

                string state = "Connected";
                try { if (logic != null && logic.State != null) state = StripState(logic.State.GetType().Name); } catch { }

                string controllerId = "";
                string name = "(connecting)";
                string clan = "";

                Player player;
                if (players != null && peer != null && players.TryGetPlayer(peer, out player) && player != null)
                {
                    controllerId = player.ControllerId ?? "";
                    name = ResolveHeroName(objects, player.HeroId, controllerId);
                    clan = ResolveClanName(objects, player.ClanId);
                }

                sb.Append("player=")
                  .Append(Clean(controllerId)).Append('|')
                  .Append(Clean(name)).Append('|')
                  .Append(Clean(clan)).Append('|')
                  .Append(Clean(state))
                  .AppendLine();
                count++;
            }
            return count;
        }

        private static IEnumerable<KeyValuePair<NetPeer, IConnectionLogic>> EnumerateConnections(IConnectionCollection connections)
        {
            // ConnectionCollection exposes the live dictionary; fall back to the IEnumerable<IConnectionLogic> otherwise.
            var concrete = connections as ConnectionCollection;
            if (concrete != null)
                return concrete.ConnectionStates;

            var list = new List<KeyValuePair<NetPeer, IConnectionLogic>>();
            foreach (var logic in connections)
                list.Add(new KeyValuePair<NetPeer, IConnectionLogic>(logic != null ? logic.Peer : null, logic));
            return list;
        }

        private static string ResolveHeroName(IObjectManager objects, string heroId, string fallback)
        {
            try
            {
                if (objects != null && !string.IsNullOrEmpty(heroId) &&
                    objects.TryGetObject<Hero>(heroId, out var hero) && hero != null)
                {
                    var n = hero.Name != null ? hero.Name.ToString() : null;
                    if (!string.IsNullOrEmpty(n)) return n;
                }
            }
            catch { }
            return string.IsNullOrEmpty(fallback) ? "(connecting)" : fallback;
        }

        private static string ResolveClanName(IObjectManager objects, string clanId)
        {
            try
            {
                if (objects != null && !string.IsNullOrEmpty(clanId) &&
                    objects.TryGetObject<Clan>(clanId, out var clan) && clan != null)
                {
                    var n = clan.Name != null ? clan.Name.ToString() : null;
                    if (!string.IsNullOrEmpty(n)) return n;
                }
            }
            catch { }
            return "";
        }

        // ------------------------------------------------------------------ commands

        private void TryProcessCommand()
        {
            string command = null;
            try
            {
                if (!File.Exists(commandPath)) return;
                foreach (var raw in File.ReadAllLines(commandPath))
                {
                    var line = raw.Trim();
                    if (line.StartsWith("cmd=", StringComparison.OrdinalIgnoreCase))
                    {
                        command = line.Substring(4).Trim();
                        break;
                    }
                }
                try { File.Delete(commandPath); } catch { }
            }
            catch (Exception ex)
            {
                Logger.Verbose(ex, "[ConsoleBridge] command read failed");
                return;
            }

            if (string.IsNullOrEmpty(command)) return;

            bool ok;
            string msg;
            try { ok = Dispatch(command, out msg); }
            catch (Exception ex) { ok = false; msg = ex.Message; }

            WriteAck(ok, msg);
            Logger.Information("[ConsoleBridge] command '{Cmd}' -> {Ok}: {Msg}", command, ok, msg);
        }

        private bool Dispatch(string command, out string msg)
        {
            var parts = command.Split(new[] { ' ' }, 2);
            var verb = parts[0].ToLowerInvariant();
            var arg = parts.Length > 1 ? parts[1].Trim() : "";

            switch (verb)
            {
                case "save": return DoSave(out msg);
                case "pause": return DoTime(TimeControlEnum.Pause, "Time paused.", out msg);
                case "resume": return DoTime(TimeControlEnum.Play_1x, "Time resumed (1x).", out msg);
                case "speed":
                    return arg == "2"
                        ? DoTime(TimeControlEnum.Play_2x, "Fast-forward (2x).", out msg)
                        : DoTime(TimeControlEnum.Play_1x, "Time set to 1x.", out msg);
                case "menu": return DoMenu(out msg);
                case "kick": return DoKick(arg, out msg);
                case "rename": return DoRename(arg, out msg);
                default:
                    msg = "Unknown command: " + verb;
                    return false;
            }
        }

        private static bool DoSave(out string msg)
        {
            if (Campaign.Current == null) { msg = "No active campaign."; return false; }
            msg = SaveDebugCommand.ForceAutoSave(new List<string>());
            return true;
        }

        private static bool DoTime(TimeControlEnum mode, string okMsg, out string msg)
        {
            if (Campaign.Current == null) { msg = "No active campaign."; return false; }
            if (!ContainerProvider.TryResolve<ITimeControlInterface>(out var time) || time == null)
            {
                msg = "Time control unavailable.";
                return false;
            }
            time.ServerSetTimeControl(mode);
            msg = okMsg;
            return true;
        }

        private static bool DoMenu(out string msg)
        {
            if (!ContainerProvider.TryResolve<IGameStateInterface>(out var gameState) || gameState == null)
            {
                msg = "Game state interface unavailable.";
                return false;
            }
            gameState.GoToMainMenu();
            msg = "Returning to main menu.";
            return true;
        }

        private static bool DoKick(string controllerId, out string msg)
        {
            if (string.IsNullOrEmpty(controllerId)) { msg = "No player id given."; return false; }
            if (!ContainerProvider.TryResolve<IConnectionCollection>(out var connections) || connections == null)
            {
                msg = "Connection registry unavailable.";
                return false;
            }
            ContainerProvider.TryResolve<IPlayerManager>(out var players);
            if (players == null) { msg = "Player registry unavailable."; return false; }

            foreach (var kvp in EnumerateConnections(connections))
            {
                var peer = kvp.Key;
                if (peer == null) continue;
                Player p;
                if (players.TryGetPlayer(peer, out p) && p != null &&
                    string.Equals(p.ControllerId, controllerId, StringComparison.Ordinal))
                {
                    peer.Disconnect();
                    msg = "Kicked player " + controllerId + ".";
                    return true;
                }
            }
            msg = "Player not found (already gone?).";
            return false;
        }

        private static bool DoRename(string arg, out string msg)
        {
            msg = "";
            int sp = arg.IndexOf(' ');
            if (sp <= 0) { msg = "Usage: rename <id> <name>"; return false; }
            var id = arg.Substring(0, sp).Trim();
            var name = arg.Substring(sp + 1).Trim();
            if (string.IsNullOrEmpty(name)) { msg = "Empty name."; return false; }

            if (!ContainerProvider.TryResolve<IPlayerManager>(out var players) || players == null)
            { msg = "Player registry unavailable."; return false; }
            ContainerProvider.TryResolve<IObjectManager>(out var objects);

            if (!players.TryGetPlayer(id, out var player) || player == null) { msg = "Player not found."; return false; }
            if (objects == null || string.IsNullOrEmpty(player.HeroId) ||
                !objects.TryGetObject<Hero>(player.HeroId, out var hero) || hero == null)
            { msg = "Player hero not found."; return false; }

            hero.SetName(new TextObject(name, null), new TextObject(name, null));
            msg = "Renamed to " + name + ".";
            return true;
        }

        private void WriteAck(bool ok, string msg)
        {
            var sb = new StringBuilder();
            sb.AppendLine("ts=" + DateTime.Now.ToString("HH:mm:ss"));
            sb.AppendLine("ok=" + (ok ? "1" : "0"));
            sb.AppendLine("msg=" + Clean(msg ?? ""));
            SafeWrite(ackPath, sb.ToString());
        }

        // ------------------------------------------------------------------ helpers

        private static string SafeCwd()
        {
            try { return Directory.GetCurrentDirectory(); }
            catch { return AppDomain.CurrentDomain.BaseDirectory; }
        }

        private static void SafeWrite(string path, string content)
        {
            try { File.WriteAllText(path, content); }
            catch (Exception ex) { Logger.Verbose(ex, "[ConsoleBridge] write failed: {Path}", path); }
        }

        private static string StripState(string typeName)
        {
            if (string.IsNullOrEmpty(typeName)) return "Connected";
            return typeName.EndsWith("State", StringComparison.Ordinal)
                ? typeName.Substring(0, typeName.Length - "State".Length)
                : typeName;
        }

        private static string Clean(string s)
        {
            if (string.IsNullOrEmpty(s)) return "";
            return s.Replace('|', '/').Replace('\r', ' ').Replace('\n', ' ').Trim();
        }
    }
}
